version: '3.7'
services:
  db:
    image: ${DOCKER_IMAGE_DB}
    restart: always
    container_name: ${SERVICE_NAME}_${CONTAINER_NAME_DB}
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBTABLE}
    volumes:
      - wiki_db:/var/lib/postgres/data
    networks:
      - ${SERVICE_NAME}

networks:
  wiki:
    name: ${SERVICE_NAME}
  webproxy:
    external:
      name: ${WEBPROXY_NETWORK}

volumes:
  wiki_db:
