version: '3.7'
services:
  server:
    image: ${DOCKER_IMAGE_SERVER}:${WIKI_VERSION}
    container_name: ${SERVICE_NAME}_${CONTAINER_NAME_SERVER}
    ports:
    - ${IP_ADDRESS}:${EXTERNAL_PORT}:3000
    depends_on:
      - db
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    networks:
      - ${SERVICE_NAME}

  db:
    image: ${DOCKER_IMAGE_DB}
    container_name: ${SERVICE_NAME}_${CONTAINER_NAME_DB}
    # ports:
    #   - "${DB_PORT}:3306"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - wiki_db:/var/lib/mysql
    networks:
      - ${SERVICE_NAME}

networks:
  wiki:
    name: ${SERVICE_NAME}

volumes:
  wiki_db:
